# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f0195b79213506ed64af31559288bc312739fbe6607d5f42482ea894aead612bd7f371cdcc9d5433adbd72ba386ac48aa4381cb830e564025a7d8493fd442555

test:
  secret_key_base: 8ecdf0aaab813ca06a2cc4dd69de3b2b970546e44cbf4a202536d84a49f5c7bc4c1692290a5212905aa47d8670ac7ea6039c4e228dd759781794869e8a9517ee

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
