require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe GoodGuysController, :type => :controller do

  # This should return the minimal set of attributes required to create a valid
  # GoodGuy. As you add validations to GoodGuy, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # GoodGuysController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all good_guys as @good_guys" do
      good_guy = GoodGuy.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:good_guys)).to eq([good_guy])
    end
  end

  describe "GET show" do
    it "assigns the requested good_guy as @good_guy" do
      good_guy = GoodGuy.create! valid_attributes
      get :show, {:id => good_guy.to_param}, valid_session
      expect(assigns(:good_guy)).to eq(good_guy)
    end
  end

  describe "GET new" do
    it "assigns a new good_guy as @good_guy" do
      get :new, {}, valid_session
      expect(assigns(:good_guy)).to be_a_new(GoodGuy)
    end
  end

  describe "GET edit" do
    it "assigns the requested good_guy as @good_guy" do
      good_guy = GoodGuy.create! valid_attributes
      get :edit, {:id => good_guy.to_param}, valid_session
      expect(assigns(:good_guy)).to eq(good_guy)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new GoodGuy" do
        expect {
          post :create, {:good_guy => valid_attributes}, valid_session
        }.to change(GoodGuy, :count).by(1)
      end

      it "assigns a newly created good_guy as @good_guy" do
        post :create, {:good_guy => valid_attributes}, valid_session
        expect(assigns(:good_guy)).to be_a(GoodGuy)
        expect(assigns(:good_guy)).to be_persisted
      end

      it "redirects to the created good_guy" do
        post :create, {:good_guy => valid_attributes}, valid_session
        expect(response).to redirect_to(GoodGuy.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved good_guy as @good_guy" do
        post :create, {:good_guy => invalid_attributes}, valid_session
        expect(assigns(:good_guy)).to be_a_new(GoodGuy)
      end

      it "re-renders the 'new' template" do
        post :create, {:good_guy => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested good_guy" do
        good_guy = GoodGuy.create! valid_attributes
        put :update, {:id => good_guy.to_param, :good_guy => new_attributes}, valid_session
        good_guy.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested good_guy as @good_guy" do
        good_guy = GoodGuy.create! valid_attributes
        put :update, {:id => good_guy.to_param, :good_guy => valid_attributes}, valid_session
        expect(assigns(:good_guy)).to eq(good_guy)
      end

      it "redirects to the good_guy" do
        good_guy = GoodGuy.create! valid_attributes
        put :update, {:id => good_guy.to_param, :good_guy => valid_attributes}, valid_session
        expect(response).to redirect_to(good_guy)
      end
    end

    describe "with invalid params" do
      it "assigns the good_guy as @good_guy" do
        good_guy = GoodGuy.create! valid_attributes
        put :update, {:id => good_guy.to_param, :good_guy => invalid_attributes}, valid_session
        expect(assigns(:good_guy)).to eq(good_guy)
      end

      it "re-renders the 'edit' template" do
        good_guy = GoodGuy.create! valid_attributes
        put :update, {:id => good_guy.to_param, :good_guy => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested good_guy" do
      good_guy = GoodGuy.create! valid_attributes
      expect {
        delete :destroy, {:id => good_guy.to_param}, valid_session
      }.to change(GoodGuy, :count).by(-1)
    end

    it "redirects to the good_guys list" do
      good_guy = GoodGuy.create! valid_attributes
      delete :destroy, {:id => good_guy.to_param}, valid_session
      expect(response).to redirect_to(good_guys_url)
    end
  end

end
